import Providers from '@/src/provider'
import { Inter } from 'next/font/google'
import Script from 'next/script'
import './globals.css'
import Navbar from '@/src/components/Navbar'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

<Script src="https://docs.getgrist.com/grist-plugin-api.js"></Script>
      <body className={inter.className}>
        <Providers>
<Navbar/>
				{children}</Providers>

			</body>
    </html>
  )
}
